### ISSUE TITLE
Tu Anh - JS Efficiency

### ISSUE THREAD

**Issue by tuanhrex** [tuanhrex/treasure-grab#2]
As of now, I'm trying out two methods to build out my maze.  One is constructor function (line 30-69)

![image](https://user-images.githubusercontent.com/73137920/97894581-ac214880-1d00-11eb-8e39-fa6e253ebd18.png)

The other is just a simple function (line 14-27)
![image](https://user-images.githubusercontent.com/73137920/97894690-cc510780-1d00-11eb-965b-5a9511fb726a.png)

I'm just curious as to which would be more efficient in building out my maze before I continue. I feel like the simple function would be quicker.

**Comment by mkzarra** [comment]
> I'm just curious as to which would be more efficient in building out my maze before I continue. I feel like the simple function would be quicker.

Either method works fine. Don't over engineer a solution if you got one that works well. Less code doesn't necessarily mean better code, but the function is easier to read.
